rodbt/urls.py
from django.urls import path

from . import views


app_name = 'rodbt'
urlpatterns = [
    path('', views.index, name='index'),

    path(
        'journals/',
        views.JournalListView.as_view(),
        name='journals'
    ),
    path(
        'journals/create/',
        views.JournalCreateView.as_view(),
        name='journal-create'
    ),
    path(
        'journals/<int:pk>/',
        views.JournalDetailView.as_view(),
        name='journal-detail'
    ),

    path(
        'questions/',
        views.QuestionListView.as_view(),
        name='questions'
    ),
    path(
        'questions/create/',
        views.QuestionCreateView.as_view(),
        name='question-create'
    ),
    path(
        'questions/<int:pk>/',
        views.QuestionDetailView.as_view(),
        name='question-detail'
    ),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock title %}</title>
    </head>
    <body>
        <main>
            <a
                href="https://github.com/brucestull/health-activity-tracker"
                target="_blank"
                >
                <code>health-activity-tracker</code> GitHub Repository
            </a>
            <br>

            {% if user.registration_accepted %}
            <a
                href={% url 'dashboard' %}
                >
                Dashboard
            </a>
            <br>
            <a
                href={% url 'rodbt:journals' %}
                >
                Journals
            </a>
            <br>
            <a
                href={% url 'rodbt:journal-create' %}
                >
                Create New Journal Entry
            </a>
            <br>
            <a
                href={% url 'rodbt:questions' %}
                >
                Questions
            </a>
            <br>
            <a
                href={% url 'rodbt:question-create' %}
                >
                Create New Question
            </a>
            <br>
            {% endif %}

            {% if user.is_staff %}
                {% include 'staff.html' %}
            {% endif %}

            {% include 'user.html' %}

            {% block content %}
            {% endblock content %}
        </main>
    </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}
    {{ the_site_name }}
{% endblock %}

{% block content %}
<h1>Home</h1>

{% endblock %}

templates/registered_user.html
{% comment %} Template for links related to 'registration_accepted' {% endcomment %}

<div>
    {% comment %} 'registration_accepted'-related links {% endcomment %}
</div>

templates/staff.html
<div>
    <a
        href={% url 'admin:index' %}
        >
        Django Admin Interface
    </a>
    <br>
</div>

templates/user.html
<div>
    <a href="{% url 'home' %}">Home</a>
    <br>
    {% if user.is_authenticated %}
        <span>Greetings, {{ user.username | capfirst }}!</span>
        <br>
        <a href="{% url 'logout' %}">Log Out</a>
        |
        <a href="{% url 'edit_profile' user.id %}">Edit Profile</a>
        |
        <a href="{% url 'password_change' %}">Password Change</a>
        |
        <a href="{% url 'password_reset' %}">Password Reset</a>
    {% else %}
        <p>We are not sure who you are, you are welcome to do one of the following:</p>
        <a href="{% url 'login' %}">Log In</a>
        |
        <a href="{% url 'signup' %}">Sign Up</a>
    {% endif %}
</div>